baseURL = 'https://zoe-plank-site.netlify.app/'
languageCode = 'en-us'
title = 'Zoe Plank Site'
theme = 'ananke'

#Metadata 
description = "Welcome to my site! Take a look around to learn more about me."

#Parameters 
[params]
     name = "Zoe Plank"
     bio = "Prospective MS in Data Science June 2024"
     linkedin = "https://www.linkedin.com/in/zoeplank/"
     github = "https://github.com/zplank/zoe-plank-sitev3/tree/master"
     email = "zoeplank@gmail.com"

[home]
  content = "main-content"

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"